// <auto-generated />
using System;
using FYP_QS_CODE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYP_QS_CODE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025064028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FYP_QS_CODE.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AgeGroupRestriction")
                        .HasColumnType("int")
                        .HasColumnName("ageGroupRestriction");

                    b.Property<int?>("AutoCreateWhen")
                        .HasColumnType("int")
                        .HasColumnName("autoCreateWhen");

                    b.Property<int?>("CancellationFreeze")
                        .HasColumnType("int")
                        .HasColumnName("cancellationfreeze");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int?>("EventTag")
                        .HasColumnType("int")
                        .HasColumnName("event_tag");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("feeAmount");

                    b.Property<int?>("FeeType")
                        .HasColumnType("int")
                        .HasColumnName("feeType");

                    b.Property<int?>("GameFeature")
                        .HasColumnType("int")
                        .HasColumnName("gameFeature");

                    b.Property<string>("GameName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gameName");

                    b.Property<int?>("GenderRestriction")
                        .HasColumnType("int")
                        .HasColumnName("genderRestriction");

                    b.Property<int?>("HostRole")
                        .HasColumnType("int")
                        .HasColumnName("hostrole");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<decimal?>("MaxRankRestriction")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("maxRankRestriction");

                    b.Property<decimal?>("MinRankRestriction")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("minRankRestriction");

                    b.Property<int?>("NumPlayer")
                        .HasColumnType("int")
                        .HasColumnName("num_player");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int")
                        .HasColumnName("privacy");

                    b.Property<int?>("RecurringWeek")
                        .HasColumnType("int")
                        .HasColumnName("recurringWeek");

                    b.Property<int?>("Repeat")
                        .HasColumnType("int")
                        .HasColumnName("repeat");

                    b.Property<int?>("ScheduleType")
                        .HasColumnType("int")
                        .HasColumnName("schedule_type");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startTime");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.ToTable("schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
